version: '3.8'

services:
  dev:
    image: dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ../data:/data
    working_dir: /app
    command: sleep infinity